# 应用配置
USERNAME: "ebike"
PASSWD: "c33367701511b4f6020ec61ded352059"
TOKEN_WEIXIU: "eyJhbGciOiJIUzM4NCJ9.eyJyYW5kb21LZXkiOiJmYWI0MTJlMS0wYjk3LTRmMmMtOGM3Ni02MzAzNzk5NDQ4ZTkiLCJyZXBhaXJlcklkIjo2LCJleHBpcmVUaW1lIjoxNzIwNzc3MDA1MDUyLCJsb2dpblRpbWUiOjE3MTgxODUwMDUwNTIsIm5pY2tuYW1lIjoi5rWL6K-VODE4MyIsImlhdCI6MTcxODE4NTAwNX0.zMV9Pgp6roZaMc_p_7w3dxDF1xEHpInXR6Bl4WeAzqOQKcEhiXOotuhgFaKsMj2T"  # 请填入实际token
PROJCET_URL: "https://api-c.ebk365.com:26887/b"

# API签名配置
app_key: "apiFox"
platform: "apiFox"
secret: "53c8eae1c4e4ecd5adb66a6b8b47a45f"

# 日志配置
log_level: INFO    